// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductionCar.Data;

#nullable disable

namespace ProductionCar.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductionCar.Models.PlanningDetail", b =>
                {
                    b.Property<int>("DetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailID"));

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DayOrder")
                        .HasColumnType("int");

                    b.Property<int>("DistributedPlanning")
                        .HasColumnType("int");

                    b.Property<bool>("IsHoliday")
                        .HasColumnType("bit");

                    b.Property<int>("OriginalPlanning")
                        .HasColumnType("int");

                    b.Property<int>("PlanningID")
                        .HasColumnType("int");

                    b.HasKey("DetailID");

                    b.HasIndex("PlanningID");

                    b.ToTable("PlanningDetails");
                });

            modelBuilder.Entity("ProductionCar.Models.PlanningHeader", b =>
                {
                    b.Property<int>("PlanningID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanningID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InputDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalActiveDays")
                        .HasColumnType("int");

                    b.Property<int>("TotalProduction")
                        .HasColumnType("int");

                    b.HasKey("PlanningID");

                    b.ToTable("PlanningHeaders");
                });

            modelBuilder.Entity("ProductionCar.Models.PlanningDetail", b =>
                {
                    b.HasOne("ProductionCar.Models.PlanningHeader", "Header")
                        .WithMany("Details")
                        .HasForeignKey("PlanningID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PlanningDetails_PlanningHeaders");

                    b.Navigation("Header");
                });

            modelBuilder.Entity("ProductionCar.Models.PlanningHeader", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
